"""
visualize_local_complexity.py

Visualizes voxel-level Local Complexity (LC) from CSV files generated by
compute_local_complexity_unet.py.

Point TRUE_POSITIVE_DIR and FALSE_POSITIVE_DIR at folders that contain
the respective CSV files.  All .csv files inside each directory are loaded
and concatenated before plotting, so you can aggregate across many scans.

If both types live in the same directory, set TP_SUFFIX / FP_SUFFIX so the
loader can tell them apart (e.g. "_true_positive_voxel" / "_false_positive").
Leave a suffix blank ("") to load every .csv in that directory.

Two plots are produced:
  1. Total LC breakdown  -- horizontal stacked bars showing what % of TP/FP
     voxels have total_lc = 0, = 1, or > 1.
  2. Per-UNet-layer LC breakdown  -- for each of the 14 hookable layers,
     side-by-side stacked bars (TP vs FP) showing the same three categories,
     so you can see which layer best distinguishes the two groups.

Plots are saved to OUTPUT_DIR.
"""

import os
import glob
import warnings
from typing import Optional, List

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

warnings.filterwarnings("ignore")

# -------------------------------------------------------------
#  CONFIGURATION
# -------------------------------------------------------------

# Directories that contain the TP / FP CSV files
TRUE_POSITIVE_DIR  = "log_local_complexity/unet_td1/hypo_3/true_positive_voxels"
FALSE_POSITIVE_DIR = "log_local_complexity/unet_td1/hypo_3/false_positive_voxels"

# Optional suffix filter (filename must contain this string).
# Useful when both dirs are the same folder.
TP_SUFFIX = ""   # set to "" to load all CSVs in the dir
FP_SUFFIX = ""        # set to "" to load all CSVs in the dir

OUTPUT_DIR = "log_local_complexity/unet_td1/hypo_3/plots"

# Human-readable label used in the output filename
PLOT_PREFIX = "combined"

# -------------------------------------------------------------
#  LAYER ORDER  (matches CSV column order)
# -------------------------------------------------------------

LAYER_COLS = [
    "enc_0_0", "enc_0_1",
    "enc_1_0", "enc_1_1",
    "enc_2_0", "enc_2_1",
    "enc_3_0", "enc_3_1",
    "dec_4_0", "dec_4_1",
    "dec_3_0", "dec_3_1",
    "dec_2_0", "dec_2_1",
]

# -------------------------------------------------------------
#  COLOURS
# -------------------------------------------------------------

COL_ZERO = "#4CAF50"   # green  -- LC = 0
COL_ONE  = "#FF9800"   # orange -- LC = 1
COL_GT1  = "#7B1FA2"   # purple -- LC > 1

PAL_TP = "#2196F3"     # blue
PAL_FP = "#E53935"     # red

# -------------------------------------------------------------
#  HELPERS
# -------------------------------------------------------------

def _load_single_csv(path: str) -> Optional[pd.DataFrame]:
    """Load one voxel-LC CSV and return only the voxel rows."""
    try:
        df = pd.read_csv(path, skiprows=5)
    except Exception as e:
        print(f"  [WARN] Could not read {path}: {e}")
        return None
    df.columns = df.columns.str.strip()
    df = df[df["type"] == "voxel"].copy()
    if df.empty:
        return None
    for col in ["total_lc"] + LAYER_COLS:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)
    return df


def load_dir(directory: str, suffix: str, label: str) -> Optional[pd.DataFrame]:
    """
    Load all CSV files from *directory* whose filename contains *suffix*
    (pass suffix="" to load every .csv in the folder).
    Returns a single concatenated DataFrame, or None if nothing was found.
    """
    if not os.path.isdir(directory):
        print(f"[WARN] {label} directory not found: {directory}")
        return None

    all_csvs = sorted(glob.glob(os.path.join(directory, "*.csv")))
    if suffix:
        all_csvs = [p for p in all_csvs if suffix in os.path.basename(p)]

    if not all_csvs:
        print(f"[WARN] No CSVs matched for {label} in {directory} (suffix={repr(suffix)})")
        return None

    frames: List[pd.DataFrame] = []
    for path in all_csvs:
        df = _load_single_csv(path)
        if df is not None:
            df["source_file"] = os.path.basename(path)
            frames.append(df)
            print(f"    {label} <- {os.path.basename(path)}  ({len(df):,} voxels)")

    if not frames:
        return None

    combined = pd.concat(frames, ignore_index=True)
    n = len(combined)
    zero_pct = 100.0 * (combined["total_lc"] == 0).sum() / n
    one_pct  = 100.0 * (combined["total_lc"] == 1).sum() / n
    gt1_pct  = 100.0 * (combined["total_lc"] >  1).sum() / n
    print(f"  {label:>3s} total: {n:>7,} voxels from {len(frames)} file(s) | "
          f"zero={zero_pct:.1f}%  one={one_pct:.1f}%  >1={gt1_pct:.1f}%")
    return combined


def breakdown(series: pd.Series) -> tuple:
    """Return (pct_zero, pct_one, pct_gt1) for a Series of LC counts."""
    n = len(series)
    return (
        100.0 * (series == 0).sum() / n,
        100.0 * (series == 1).sum() / n,
        100.0 * (series >  1).sum() / n,
    )


def label_bar(ax, x, bottom, height, txt, min_pct=1.0):
    """Draw a centred white label inside a bar segment if tall enough."""
    if height >= min_pct:
        ax.text(x, bottom + height / 2, txt,
                ha="center", va="center",
                fontsize=7, fontweight="bold", color="white")


def savefig(fig, name: str):
    path = os.path.join(OUTPUT_DIR, name)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved -> {path}")


# -------------------------------------------------------------
#  LOAD DATA
# -------------------------------------------------------------

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("\n-- Loading CSVs --")
df_tp = load_dir(TRUE_POSITIVE_DIR,  TP_SUFFIX, "TP")
df_fp = load_dir(FALSE_POSITIVE_DIR, FP_SUFFIX, "FP")

datasets = [(lbl, df) for lbl, df in [("TP", df_tp), ("FP", df_fp)] if df is not None]
if not datasets:
    raise RuntimeError("No CSV files could be loaded. Check your paths.")

print("\n-- Generating plots --")


# =============================================================
#  PLOT 1 -- Total LC breakdown: horizontal stacked bars
# =============================================================
#
#  One bar per group (TP / FP).
#  Each bar shows three segments: LC=0 | LC=1 | LC>1
#  Percentages are printed inside each segment.

fig, ax = plt.subplots(figsize=(11, 2.5 + 0.9 * len(datasets)))
fig.suptitle("Total LC Breakdown per Voxel Type", fontweight="bold", fontsize=13)

legend_patches = [
    mpatches.Patch(color=COL_ZERO, label="LC = 0  (no activation changes)"),
    mpatches.Patch(color=COL_ONE,  label="LC = 1  (one activation change)"),
    mpatches.Patch(color=COL_GT1,  label="LC > 1  (multiple changes)"),
]

for i, (lbl, df) in enumerate(datasets):
    z, o, g = breakdown(df["total_lc"])
    bar_color = PAL_TP if lbl == "TP" else PAL_FP

    ax.barh(i, z,          left=0,     color=COL_ZERO, edgecolor="white", linewidth=0.6, height=0.55)
    ax.barh(i, o,          left=z,     color=COL_ONE,  edgecolor="white", linewidth=0.6, height=0.55)
    ax.barh(i, g,          left=z + o, color=COL_GT1,  edgecolor="white", linewidth=0.6, height=0.55)

    # Percentage labels inside segments
    if z >= 1.0:
        ax.text(z / 2,          i, f"{z:.1f}%", ha="center", va="center", fontsize=9, fontweight="bold", color="white")
    if o >= 1.0:
        ax.text(z + o / 2,      i, f"{o:.2f}%", ha="center", va="center", fontsize=9, fontweight="bold", color="white")
    if g >= 1.0:
        ax.text(z + o + g / 2,  i, f"{g:.2f}%", ha="center", va="center", fontsize=9, fontweight="bold", color="white")

    # Bold label on the left with voxel count
    ax.text(-1, i, f"{lbl}  (n={len(df):,})", ha="right", va="center",
            fontsize=10, fontweight="bold",
            color=bar_color)

ax.set_xlim(0, 100)
ax.set_ylim(-0.6, len(datasets) - 0.4)
ax.set_yticks([])
ax.set_xlabel("Percentage of voxels (%)", fontsize=10)
ax.axvline(100, color="gray", linewidth=0.4)
ax.legend(handles=legend_patches, loc="lower right", fontsize=9, framealpha=0.9)
ax.set_title("Green = network certain (zero activation changes)  |  "
             "Red = network uncertain (multiple changes)", fontsize=9, style="italic")

plt.tight_layout()
savefig(fig, f"{PLOT_PREFIX}_lc_breakdown_total.png")


# =============================================================
#  PLOT 2 -- Per-UNet-layer LC breakdown: TP vs FP side-by-side
# =============================================================
#
#  X-axis: 14 UNet layers (enc_0_0 ... dec_2_1)
#  For each layer: two stacked bars side by side -- TP (blue edge) and FP (red edge)
#  Each bar: LC=0 (green) / LC=1 (orange) / LC>1 (red), stacked.
#  The layer where the two bars look most different is the best discriminator.

n_layers = len(LAYER_COLS)
x = np.arange(n_layers)
w = 0.38          # width of each bar
gap = 0.03        # gap between the two bars in a pair

fig, ax = plt.subplots(figsize=(17, 7))
fig.suptitle("Per-UNet-Layer LC Breakdown: TP vs FP", fontweight="bold", fontsize=13)

for col_idx, col in enumerate(LAYER_COLS):
    for grp_idx, (lbl, df) in enumerate(datasets):
        xpos = col_idx + (grp_idx - (len(datasets) - 1) / 2.0) * (w + gap)
        edge = PAL_TP if lbl == "TP" else PAL_FP

        z, o, g = breakdown(df[col])

        # Stacked bars: zero at bottom, then one, then gt1
        ax.bar(xpos, z,     width=w, color=COL_ZERO, edgecolor=edge, linewidth=1.2)
        ax.bar(xpos, o,     width=w, bottom=z,     color=COL_ONE,  edgecolor=edge, linewidth=1.2)
        ax.bar(xpos, g,     width=w, bottom=z + o, color=COL_GT1,  edgecolor=edge, linewidth=1.2)

        # Labels inside segments (only if segment is wide enough to read)
        label_bar(ax, xpos, 0,     z,     f"{z:.1f}%", min_pct=3.0)
        label_bar(ax, xpos, z,     o,     f"{o:.2f}%", min_pct=1.5)
        label_bar(ax, xpos, z + o, g,     f"{g:.2f}%", min_pct=1.5)

ax.set_xticks(x)
ax.set_xticklabels(LAYER_COLS, rotation=45, ha="right", fontsize=9)
ax.set_ylabel("% of voxels", fontsize=11)
ax.set_ylim(0, 105)
ax.set_xlim(-0.6, n_layers - 0.4)

# Encoder / decoder shading
enc_end_idx = LAYER_COLS.index("enc_3_1")
ax.axvspan(-0.5,            enc_end_idx + 0.5, alpha=0.04, color="steelblue",  zorder=0)
ax.axvspan(enc_end_idx + 0.5, n_layers - 0.5, alpha=0.04, color="darkorange", zorder=0)
ax.text(enc_end_idx / 2,              103, "Encoder",  ha="center", va="top", fontsize=9, color="steelblue",  alpha=0.9)
ax.text(enc_end_idx + (n_layers - 1 - enc_end_idx) / 2, 103, "Decoder", ha="center", va="top", fontsize=9, color="darkorange", alpha=0.9)
ax.axvline(enc_end_idx + 0.5, color="gray", linewidth=0.8, linestyle="--", alpha=0.5)

# Legend: LC categories + TP/FP edge colour indicator
legend_patches = [
    mpatches.Patch(color=COL_ZERO, label="LC = 0"),
    mpatches.Patch(color=COL_ONE,  label="LC = 1"),
    mpatches.Patch(color=COL_GT1,  label="LC > 1"),
    mpatches.Patch(facecolor="white", edgecolor=PAL_TP, linewidth=2,
                   label=f"TP (n={len(df_tp):,})" if df_tp is not None else "TP"),
    mpatches.Patch(facecolor="white", edgecolor=PAL_FP, linewidth=2,
                   label=f"FP (n={len(df_fp):,})" if df_fp is not None else "FP"),  # noqa: E501
]
ax.legend(handles=legend_patches, loc="lower right", fontsize=9, framealpha=0.9)
ax.set_title("Blue outline = TP bar  |  Red outline = FP bar  |  "
             "Layer with biggest TP/FP difference = best discriminator", fontsize=9, style="italic")

plt.tight_layout()
savefig(fig, f"{PLOT_PREFIX}_lc_breakdown_per_layer.png")

print("\n-- All done --")
print(f"Plots saved to: {os.path.abspath(OUTPUT_DIR)}/")
